name: Check Outdated Version Pinning
on:
  workflow_dispatch: {}
permissions:
  issues: write
  contents: read
jobs:
  check-pinning-dates:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Validate JSON Schema
      shell: pwsh
      run: ./helpers/CheckOutdatedVersionPinning.ps1
      env:
        GH_TOKEN: ${{ github.token }}
