name: Test Docker Images
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  test-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
        - images/ubuntu-slim
    steps:
    - uses: actions/checkout@v6
    - name: Run test.sh
      working-directory: ${{ matrix.directory }}
      run: ./test.sh
