name: PowerShell Tests
on:
  workflow_dispatch: {}
jobs:
  powershell-tests:
    name: PowerShell tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
    - name: Run Software Report module tests
      shell: pwsh
      run: '$ErrorActionPreference = "Stop"

        Invoke-Pester -Output Detailed "helpers/software-report-base/tests"

        '
