name: Update release
on:
  workflow_dispatch: {}
jobs:
  Update_GitHub_release:
    runs-on: ubuntu-slim
    steps:
    - name: Update release for ${{ github.event.client_payload.ReleaseBranchName }}
      uses: actions/github-script@v8
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "const response = await github.rest.repos.getReleaseByTag({\n  owner:\
          \ context.repo.owner,\n  repo: context.repo.repo,\n  tag: \"${{ github.event.client_payload.ReleaseBranchName\
          \ }}\"\n});\ngithub.rest.repos.updateRelease({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  release_id: response.data.id,\n  prerelease:\
          \ ${{ github.event.client_payload.Prerelease }}\n});\n"
