name: Trigger Windows22 CI
run-name: Windows2022 - ${{ github.event.pull_request.title }}
on:
  workflow_dispatch: {}
defaults:
  run:
    shell: pwsh
jobs:
  Windows_2022:
    if: github.event.label.name == 'CI windows-all' || github.event.label.name ==
      'CI windows-2022'
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: windows2022
    secrets: inherit
